name: Send SMS

on:
  workflow_dispatch:
    inputs:
      phone:
        description: 'Phone Number'
        required: true
        default: ''

jobs:
  send_sms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send SMS via Abstract API
        env:
          ABSTRACT_API_KEY: ${{ secrets.ABSTRACT_API_KEY }}
        run: |
          PHONE_NUMBER="${{ github.event.inputs.phone }}"
          RESPONSE=$(curl -s "https://phonevalidation.abstractapi.com/v1/?api_key=${ABSTRACT_API_KEY}&phone=${PHONE_NUMBER}")

          # Check response and print
          echo "Response from Abstract API: $RESPONSE"
